"""empty message

Revision ID: 0d4c90987845
Revises: 5a438817a005
Create Date: 2026-05-05 22:07:00.090367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4c90987845'
down_revision: Union[str, None] = '5a438817a005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pub_recipe_request', 'feedback',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('pub_recipe_request', 'moderator_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pub_recipe_request', 'moderator_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pub_recipe_request', 'feedback',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
