"""empty message

Revision ID: 0ea7634d20dd
Revises: 99c8b4b7cb8a
Create Date: 2026-05-07 17:51:00.808570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea7634d20dd'
down_revision: Union[str, None] = '99c8b4b7cb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'updated_at')
    # ### end Alembic commands ###
