"""empty message

Revision ID: 0f4ec9580bbb
Revises: 191ff5d93af9
Create Date: 2026-04-30 22:36:02.913638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4ec9580bbb'
down_revision: Union[str, None] = '191ff5d93af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooking_session', sa.Column('status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cooking_session', 'status')
    # ### end Alembic commands ###
