"""empty message

Revision ID: 114bc5d09afd
Revises: 5e9c61cc6423
Create Date: 2026-04-23 23:45:03.400240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114bc5d09afd'
down_revision: Union[str, None] = '5e9c61cc6423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ingredient_ingredient_group_ingredient_id_fkey'), 'ingredient_ingredient_group', type_='foreignkey')
    op.drop_constraint(op.f('ingredient_ingredient_group_ingredient_group_id_fkey'), 'ingredient_ingredient_group', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient_ingredient_group', 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ingredient_ingredient_group', 'ingredient_group', ['ingredient_group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('recipe_recipe_category_recipe_id_fkey'), 'recipe_recipe_category', type_='foreignkey')
    op.drop_constraint(op.f('recipe_recipe_category_recipe_category_id_fkey'), 'recipe_recipe_category', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_recipe_category', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_recipe_category', 'recipe_category', ['recipe_category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_ingredient_group_user_id_fkey'), 'user_ingredient_group', type_='foreignkey')
    op.drop_constraint(op.f('user_ingredient_group_ingredient_group_id_fkey'), 'user_ingredient_group', type_='foreignkey')
    op.create_foreign_key(None, 'user_ingredient_group', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_ingredient_group', 'ingredient_group', ['ingredient_group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_ingredient_group', type_='foreignkey')
    op.drop_constraint(None, 'user_ingredient_group', type_='foreignkey')
    op.create_foreign_key(op.f('user_ingredient_group_ingredient_group_id_fkey'), 'user_ingredient_group', 'ingredient_group', ['ingredient_group_id'], ['id'])
    op.create_foreign_key(op.f('user_ingredient_group_user_id_fkey'), 'user_ingredient_group', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'recipe_recipe_category', type_='foreignkey')
    op.drop_constraint(None, 'recipe_recipe_category', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_recipe_category_recipe_category_id_fkey'), 'recipe_recipe_category', 'recipe_category', ['recipe_category_id'], ['id'])
    op.create_foreign_key(op.f('recipe_recipe_category_recipe_id_fkey'), 'recipe_recipe_category', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'ingredient_ingredient_group', type_='foreignkey')
    op.drop_constraint(None, 'ingredient_ingredient_group', type_='foreignkey')
    op.create_foreign_key(op.f('ingredient_ingredient_group_ingredient_group_id_fkey'), 'ingredient_ingredient_group', 'ingredient_group', ['ingredient_group_id'], ['id'])
    op.create_foreign_key(op.f('ingredient_ingredient_group_ingredient_id_fkey'), 'ingredient_ingredient_group', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###
