"""empty message

Revision ID: 191ff5d93af9
Revises: 6055d257e6ed
Create Date: 2026-04-29 23:46:06.846330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191ff5d93af9'
down_revision: Union[str, None] = '6055d257e6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooking_session', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cooking_session', sa.Column('current_step', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cooking_session', 'current_step')
    op.drop_column('cooking_session', 'last_activity')
    # ### end Alembic commands ###
