"""empty message

Revision ID: 405e0acfbb57
Revises: 70fc4eae353b
Create Date: 2026-05-01 22:42:29.609708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405e0acfbb57'
down_revision: Union[str, None] = '70fc4eae353b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('recipe_step_recipe_id_fkey'), 'recipe_step', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_step', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_step', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_step_recipe_id_fkey'), 'recipe_step', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
