"""empty message

Revision ID: 4137c60648fa
Revises: 
Create Date: 2026-04-19 00:42:35.546777

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.config import config_loader
from sqlalchemy.dialects import postgresql

from domain.entities.value_objects import RoleType

# revision identifiers, used by Alembic.
revision: str = '4137c60648fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('default_unit_measurement', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_group',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False, default=RoleType.admin),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingredient_ingredient_group',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_group_id'], ['ingredient_group.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'ingredient_group_id')
    )
    op.create_table('recipe',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('estimated_time', sa.Numeric(), nullable=True),
    sa.Column('calories_by_100grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meal_time', sa.String(length=30), nullable=False),
    sa.Column('rating_sum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chief_chat',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ingredient_group',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_group_id'], ['ingredient_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'ingredient_group_id')
    )
    op.create_table('cooking_session',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_recipe_request',
    sa.Column('feedback', sa.TEXT(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredient',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit_measurement', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_step',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_recipe',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id', 'id')
    )
    bind = op.get_bind()
    admin_settings = config_loader.app_config.admin
    if admin_settings.admin_emails and admin_settings.admin_passwords:
        emails = admin_settings.admin_emails.split(",")
        passwords = admin_settings.admin_passwords.split(",")

        if len(emails) == len(passwords):
            user_table = sa.table(
                "user",
                sa.column("id", sa.UUID),
                sa.column("email", sa.String),
                sa.column("is_email_cofirmed", sa.Boolean),
                sa.column("is_active", sa.Boolean),
                sa.column("role", sa.String),
            )
            admins = [
                {
                    "id": uuid.uuid4(),
                    "email": email.strip(),
                    "is_active": True,
                    "role": RoleType.admin.value,
                }
                for email, password in zip(emails, passwords, strict=False)
            ]

            bind.execute(user_table.insert(), admins)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipe')
    op.drop_table('recipe_step')
    op.drop_table('recipe_ingredient')
    op.drop_table('pub_recipe_request')
    op.drop_table('cooking_session')
    op.drop_table('user_ingredient_group')
    op.drop_table('user_chief_chat')
    op.drop_table('recipe')
    op.drop_table('ingredient_ingredient_group')
    op.drop_table('user')
    op.drop_table('ingredient_group')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
