"""empty message

Revision ID: 5e9c61cc6423
Revises: 47f96051d1e9
Create Date: 2026-04-21 22:37:21.122424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9c61cc6423'
down_revision: Union[str, None] = '47f96051d1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_category',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_recipe_category',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_category_id'], ['recipe_category.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'recipe_category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_recipe_category')
    op.drop_table('recipe_category')
    # ### end Alembic commands ###
