"""empty message

Revision ID: 6055d257e6ed
Revises: fa604a286899
Create Date: 2026-04-27 23:28:44.816643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6055d257e6ed'
down_revision: Union[str, None] = 'fa604a286899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Добавляем колонки с nullable=True (временно)
    op.add_column('recipe', sa.Column('spicy_level', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('difficulty_level', sa.Integer(), nullable=True))

    # 2. Заполняем существующие записи значениями по умолчанию
    op.execute("UPDATE recipe SET spicy_level = 0 WHERE spicy_level IS NULL")
    op.execute("UPDATE recipe SET difficulty_level = 1 WHERE difficulty_level IS NULL")

    # 3. Делаем колонки nullable=False
    op.alter_column('recipe', 'spicy_level', nullable=False)
    op.alter_column('recipe', 'difficulty_level', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'difficulty_level')
    op.drop_column('recipe', 'spicy_level')
    # ### end Alembic commands ###
