"""empty message

Revision ID: 70fc4eae353b
Revises: 0f4ec9580bbb
Create Date: 2026-05-01 22:40:53.418299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fc4eae353b'
down_revision: Union[str, None] = '0f4ec9580bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('recipe_ingredient_recipe_id_fkey'), 'recipe_ingredient', type_='foreignkey')
    op.drop_constraint(op.f('recipe_ingredient_ingredient_id_fkey'), 'recipe_ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredient', 'ingredient', ['ingredient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recipe_ingredient', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_ingredient', type_='foreignkey')
    op.drop_constraint(None, 'recipe_ingredient', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_ingredient_ingredient_id_fkey'), 'recipe_ingredient', 'ingredient', ['ingredient_id'], ['id'])
    op.create_foreign_key(op.f('recipe_ingredient_recipe_id_fkey'), 'recipe_ingredient', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
