"""empty message

Revision ID: 71dec417194c
Revises: 9d7990301a72
Create Date: 2026-04-26 16:02:22.417282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71dec417194c'
down_revision: Union[str, None] = '9d7990301a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index(
        "ix_ingredient_search_vector",
        "ingredient",
        ["search_vector"],
        postgresql_using="gin"
    )
    op.create_index(
        "ix_ingredient_title_trgm",
        "ingredient",
        ["title"],
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.execute("""
    CREATE OR REPLACE FUNCTION ingredient_search_vector_update()
    RETURNS trigger AS $$
    BEGIN
        NEW.search_vector :=
            to_tsvector('russian',
                coalesce(NEW.title, '') || ' ' ||
                coalesce((
                    SELECT string_agg(g.title, ' ')
                    FROM ingredient_group g
                    JOIN ingredient_ingredient_group igg
                      ON igg.ingredient_group_id = g.id
                    WHERE igg.ingredient_id = NEW.id
                ), '')
            );

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trg_ingredient_search_vector
    BEFORE INSERT OR UPDATE ON ingredient
    FOR EACH ROW
    EXECUTE FUNCTION ingredient_search_vector_update();
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION ingredient_group_link_update()
    RETURNS trigger AS $$
    BEGIN
        UPDATE ingredient i
        SET search_vector =
            to_tsvector('russian',
                i.title || ' ' ||
                (
                    SELECT string_agg(g.title, ' ')
                    FROM ingredient_group g
                    JOIN ingredient_ingredient_group igg
                      ON igg.ingredient_group_id = g.id
                    WHERE igg.ingredient_id = i.id
                )
            )
        WHERE i.id = COALESCE(NEW.ingredient_id, OLD.ingredient_id);

        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trg_ingredient_group_link
    AFTER INSERT OR DELETE ON ingredient_ingredient_group
    FOR EACH ROW
    EXECUTE FUNCTION ingredient_group_link_update();
    """)
    op.execute("""
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    """)
    op.execute("""
        UPDATE ingredient i
        SET search_vector =
            to_tsvector('russian',
                coalesce(i.title, '') || ' ' ||
                coalesce((
                    SELECT string_agg(g.title, ' ')
                    FROM ingredient_group g
                    JOIN ingredient_ingredient_group igg
                      ON igg.ingredient_group_id = g.id
                    WHERE igg.ingredient_id = i.id
                ), '')
            );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'search_vector')
    # ### end Alembic commands ###
