"""empty message

Revision ID: 99c8b4b7cb8a
Revises: 0d4c90987845
Create Date: 2026-05-06 14:27:29.775743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c8b4b7cb8a'
down_revision: Union[str, None] = '0d4c90987845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_recipe', sa.Column('added_to_favorite_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_recipe', 'added_to_favorite_at')
    # ### end Alembic commands ###
