"""empty message

Revision ID: fa604a286899
Revises: 71dec417194c
Create Date: 2026-04-26 17:27:12.900492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa604a286899'
down_revision: Union[str, None] = '71dec417194c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_category', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_recipe_category_search_vector', 'recipe_category', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_recipe_category_title_trgm', 'recipe_category', ['search_vector'], unique=False, postgresql_using='gin')
    op.execute("""
        UPDATE recipe_category
        SET search_vector = to_tsvector('russian', coalesce(title, ''));
    """)
    op.execute("""
    CREATE OR REPLACE FUNCTION recipe_category_tsv_update()
    RETURNS trigger AS $$
    BEGIN
        NEW.search_vector :=
            to_tsvector('russian', coalesce(NEW.title, ''));
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trg_recipe_category_tsv
    BEFORE INSERT OR UPDATE ON recipe_category
    FOR EACH ROW
    EXECUTE FUNCTION recipe_category_tsv_update();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_recipe_category_tsv ON recipe_category;")
    op.execute("DROP FUNCTION IF EXISTS recipe_category_tsv_update;")

    op.drop_index('ix_recipe_category_title_trgm', table_name='recipe_category', postgresql_using='gin')
    op.drop_index('ix_recipe_category_search_vector', table_name='recipe_category', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_column('recipe_category', 'search_vector')
    # ### end Alembic commands ###
