"""empty message

Revision ID: ff158c3bc536
Revises: 405e0acfbb57
Create Date: 2026-05-01 22:44:03.367674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff158c3bc536'
down_revision: Union[str, None] = '405e0acfbb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_recipe_recipe_id_fkey'), 'user_recipe', type_='foreignkey')
    op.drop_constraint(op.f('user_recipe_user_id_fkey'), 'user_recipe', type_='foreignkey')
    op.create_foreign_key(None, 'user_recipe', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_recipe', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_recipe', type_='foreignkey')
    op.drop_constraint(None, 'user_recipe', type_='foreignkey')
    op.create_foreign_key(op.f('user_recipe_user_id_fkey'), 'user_recipe', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_recipe_recipe_id_fkey'), 'user_recipe', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
