"""empty message

Revision ID: b08f9b4b2c73
Revises: fb521da33351
Create Date: 2025-06-08 16:17:23.839210

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b08f9b4b2c73"
down_revision: str | None = "fb521da33351"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column("avatar_upd_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("user", "avatar_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "avatar_path", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("client", "avatar_upd_at")
    # ### end Alembic commands ###
