"""empty message

Revision ID: f8463c4c9998
Revises: b08f9b4b2c73
Create Date: 2026-01-09 02:31:57.165636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8463c4c9998'
down_revision: Union[str, None] = 'b08f9b4b2c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_ref_rs_association_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_ref_id', sa.Integer(), nullable=False),
    sa.Column('rs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_ref_id'], ['client_ref.id'], ),
    sa.ForeignKeyConstraint(['rs_id'], ['resource_server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_ref_rs_association_table')
    op.drop_table('client_ref')
    # ### end Alembic commands ###
